export const majors = [
    "Animation",
    "Computer Engineering",
    "Computing Engineering Technology",
    "Computing Exploration",
    "Computing and Information Technologies",
    "Computer Science",
    "Cybersecurity",
    "3D Digital Design",
    "Electrical Engineering",
    "Electrical Engineering Technology",
    "Engineering Exploration",
    "Engineering Technology Exploration",
    "Film and Animation",
    "Fine Art Photography",
    "Game Arts",
    "Game Design and Development",
    "Graphic Design",
    "Humanities, Computing, and Design",
    "Human-Centered Computing",
    "Illustration",
    "Industrial Design",
    "Industrial Engineering",
    "Motion Picture Science",
    "New Media Design",
    "New Media Interactive Development",
    "Software Engineering",
    "Web and Mobile Computing",
    "Print and Graphic Media Technology",
    "Printmaking",
    "Product Design",
    "Production Option",
    "Robotics and Automation",
    "Robotics and Manufacturing",
    "Robotics",
    "Other",
];