export const roles = [
    "Full-Stack Developer",
    "Front-End Developer",
    "Back-End Developer",
    "Software Developer",
    "Cloud Developer",
    "Mobile Developer",
    "Embedded Systems Developer",
    "Video Game Developer",
    "Database Developer",
    "PHP Developer",
    "Blockchain Developer",
    "DevOps Developer",
    "VR Developer",
    "UI/UX Designer",
    "Mobile UI/UX Designer",
    "Graphic Designer",
    "Web Designer",
    "Technical Designer",
    "Video Game Designer",
    "Product Designer",
    "Visual Designer",
    "Motion Graphics Designer",
    "Packaging Designer",
    "Interior Designer",
    "Industrial Designer",
    "Mentor",
    "Video Editor",
    "Manager",
    "Project Manager",
    "Graphic Artist",
    "Instructor",
    "VFX Artist",
    "SFX Artist",
    "Marketing Specialist",
    "Cyber Security",
    "Web Developer",
    "Mobile App Developer",
    "Digital Strategist",
    "Technical Writer",
    "IT Support Specialist",
    "Music Composer",
    "Video Game Composer",
    "2D Animator",
    "Illustrator",
    "3D Animator",
    "Sound Designer",
    "Electrical Engineer",
    "Computer Engineer",
    "Mechanical Engineer",
    "Industrial Engineer",
    "2D Artist",
    "3D Artist",
    "Concept Artist",
    "Financing",
    "Film Producer",
    "Photographer",
    "Actor",
    "Voice Actor",
    "Writer",
    "Scriptwriter",
    "Level Designer",
    "Character Designer",
    "Film Director",
    "Background Artist",
    "3D Modeler",
    "Render Wrangler",
    "Fashion Designer",
    "Creative Director",
    "Art Director",
    "Social Media Manager",
    "Environment Artist",
    "AR/XR Developer",
    "Project Lead",
    "Team Lead",
    "Other",
];