//tags used for projects
//Many are temporary, as they are just what was in the data
export const tags = [
  "Game Development",
  "Roguelike",
  "FPS",
  "So Retro",
  "Rock",
  "Cooking",
  "Birthday",
  "Dirt",
  "2.5D",
  "Sandbox",
  "Adventure",
  "Shared1",
  "Shared2",
  "Wah",
  "Waah",
  "Waaah",
  "Waaaah",
  "Boring",
  "BlahBlahBlah",
  "abc",
  "12345",
  "Class Project",
  "pls help",
  "idk",
]

export const projectTypes = [
  "Video Game",
  "Analog Game",
  "Mobile Application",
  "Website",
  "Animation",
  "Film",
  "Art",
  "Music",
  "Story",
  "Computer Systems Design",
  "Software Development",
  "Product Development",
  "AI",
  "IT Support and Administration",
  "Data Science",
  "Cybersecurity",
  "Cloud Computing",
  "Robotics",
]

//Only used for profiles
export const softSkills = [
  "Problem Solving",
  "Creativity",
  "Leadership",
  "Organization",
  "Critical Thinking",
  "Public Speaking",
  "Team Work",
  "Interpersonal communication",
  "Intrapersonal communcation",
  "Innovation",
  "Work ethic",
  "Trustworthiness",
  "Flexibility",
  "Openness to criticism",
  "Decision-making",
  "Responsiveness",
  "Curiosity",
  "Professionalism",
  "Attention to detail",
  "Analytical thinking",
  "Conflict management",
  "Fast learner",
  "Database programming",
  "Organizational skills",
  "Data structures and algorithms",
  "Time management",
];

export const devSkills = [
  "C++",
  "CSS",
  "C#",
  "Operating Systems",
  "Linux",
  "Windows",
  "Full-stack Development",
  "Java",
  "Javascript",
  "SQL",
  "Debugging",
  "Visual Studio",
  "Visual Studio Code",
  "Xcode",
  "PyCharm",
  "Go",
  "Microsoft Azure",
  "API",
  "Github",
  "Git",
  "Ruby",
  "PHP",
  "C",
  "Kotlin",
  "Unity",
  "Unreal Engine",
  "Godot",
  "React",
  "Node.js",
  "OpenAI",
  "HTML",
  "Python",
  "Typescript",
  "MongoDB",
  "Vue.js",
  "Bootstrap",
  "Lua",
  "Database Programming",
  "Data Structures and Algorithms",
]

export const DesignSkills = [
  "Sketch",
  "Figma",
  "Adobe",
  "Adobe PhotoShop",
  "Canva",
  "Fotor",
  "GIMP",
  "Adobe XD",
  "Axure",
  "Adobe Illustrator",
  "Desygner",
  "Coolers",
  "Pixlr",
  "Visme",
  "Webflow",
  "Blender",
  "Procreate",
  "Autodesk Maya",
  "Krita",
  "Cinema 4D",
  "ZBrush",
  "SketchUp",
  "Photo/Video Editing",
  "Photography",
  "Adobe After Effects",
]

//Used for profiles and position listings on projects
export const proficiencies = [
  "Full-stack Development",
  "Back-end Development",
  "Front-end Development",
  "Software Development",
  "Cloud Development",
  "Mobile Development",
  "Embedded Systems Development",
  "Game Development",
  "Database Development",
  "PHP Development",
  "Blockchain Development",
  "DevOps Development",
  "AR/VR Development",
  "UI/UX Design",
  "Graphic Design",
  "Web Design",
  "Technical Design",
  "Video Game Design",
  "Product Design",
  "Visual Design",
  "Motion Graphic Design",
  "Packaging Design",
  "Interior Design",
  "Motion graphics Design",
  "Industrial Design",
  "Mentorship",
  "Video Editing",
  "Management",
  "Project Management",
  "Graphic Artist",
  "Instructor",
  "Sound Effects",
  "Marketing",
  "Cyber Security",
  "Web editor",
  "Digital Strategy",
  "Technical Writing",
  "IT"
];

//Used for profiles and projects
export const tools = [
  "C++",
  "CSS",
  "C#",
  "Operating Systems",
  "Linux",
  "Windows",
  "Full-stack development",
  "Java",
  "Javascript",
  "SQL",
  "Debugging",
  "Visual Studio",
  "Visual Studio Code",
  "Xcode",
  "PyCharm",
  "Go",
  "Mircosoft Azure",
  "API",
  "GIthub",
  "Git",
  "Ruby",
  "PHP",
  "C",
  "Kotlin",
  "Ruby",
  "Unity",
  "Sketch",
  "Figma",
  "Adobe",
  "Adobe PhotoShop",
  "Canva",
  "Fotor",
  "GIMP",
  "Adobe XD",
  "Axure",
  "Adobe Illustrator",
  "Desygner",
  "Coolers",
  "Pixlr",
  "Visme",
  "Webflow",
  "Blender",
  "Procreate",
  "Autodesk Maya",
  "Aseprite"
];

//Used for projects and profile preferences
export const projectDetails = [
  "Full-time",
  "Part-time",
  "Flexible",
  "Short-term",
  "Long-term",
  "On-site",
  "Remote",
  "Academic",
  "Personal",
  "Paid",
  "Unpaid",
]